version: "3.9"

services:
  api:
    build:
      context: ./backend
    container_name: anyware_api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - .env
    depends_on:
      - mongo
    networks:
      - anyware_net

  frontend:
    build:
      context: ./frontend
    container_name: anyware_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: "http://localhost:4000"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - anyware_net

  mongo:
    image: mongo:6.0
    container_name: anyware_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: anyware_db
    volumes:
      - mongo_data:/data/db
    networks:
      - anyware_net

volumes:
  mongo_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  anyware_net:

