version: "3.9"

services:
  api:
    build: .
    container_name: anyware_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: "mongodb://mongo:27017/anyware_db"
    depends_on:
      - mongo
    networks:
      - anyware_net

  mongo:
    image: mongo:6.0
    container_name: anyware_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: anyware_db
    volumes:
      - mongo_data:/data/db
    networks:
      - anyware_net

volumes:
  mongo_data:

networks:
  anyware_net:
